// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentExit = { sessionId: string, code: number | null, pid: number, };

export type AgentLines = { sessionId: string, lines: Array<string>, };

export type Auth = { auth: string, };

export type DaemonInfo = { url: string, token: string, };

export type Event = { event: string, payload: unknown, };

export type PtyAck = { id: string, processed: number, };

export type PtyAttach = { id: string, from: number, };

export type PtyError = { id: string, error: string, };

export type PtyExit = { id: string, code: number | null, };

export type PtyKill = { id: string, };

export type PtyResize = { id: string, cols: number, rows: number, };

export type PtySpawn = { id: string, cwd: string, command: Array<string>, cols: number, rows: number, };

export type PtyWrite = { id: string, data: string, };

export type Request = { id: number, method: string, params: unknown, };

export type Response = { id: number, ok: boolean, result?: unknown, error?: string, };

export type ToolCall = { id: bigint, sessionId: string, method: string, params: unknown, };
