// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentBinary = { path: string, };

export type ApprovalDecision = "allow" | "always" | "deny";

export type ApprovalResolution = "allow" | "always" | "deny" | "cancelled";

export type AttachedFile = { name: string, path: string, kind?: AttachedFileKind, size?: number, };

export type AttachedFileKind = "image" | "file";

export type Auth = { auth: string, };

export type Block = { id: string, role: BlockRole, text: string, at?: number, hidden?: boolean, streaming?: boolean, files?: Array<AttachedFile>, tool?: BlockTool, approval?: BlockApproval, question?: BlockQuestion, usage?: TurnUsage, };

export type BlockApproval = { requestId: number, name: string, input?: Record<string, unknown>, decided?: ApprovalDecision, };

export type BlockQuestion = { requestId: number, questions: Array<Question>, answers?: { [key in string]: string }, dismissed?: boolean, };

export type BlockRole = "user" | "assistant" | "reasoning" | "tool" | "approval" | "question" | "system";

export type BlockTool = { callId: string, name: string, title: string, status: ToolStatus, detail?: ToolDetail, };

export type BridgeInfo = { socketPath: string, token: string, exe: string, };

export type Cwd = { cwd: string, };

export type DaemonInfo = { url: string, token: string, };

export type Event = { event: string, payload: unknown, };

export type FileBytes = { mime: string, data: string, };

export type HarnessEvent = { "type": "session.started", } | { "type": "session.ended", code?: number | null, } | { "type": "session.error", message: string, } | { "type": "session.note", message: string, } | { "type": "user.message", text: string, hidden?: boolean, files?: Array<AttachedFile>, } | { "type": "system.message", text: string, } | { "type": "session.providerBound", providerSessionId: string, } | { "type": "message.delta", text: string, } | { "type": "message.completed", } | { "type": "reasoning.delta", text: string, } | { "type": "turn.completed", usage?: TurnUsage, } | { "type": "tool.started", callId: string, name: string, title: string, detail?: ToolDetail, } | { "type": "tool.updated", callId: string, title?: string, status?: ToolStatus, detail?: ToolDetail, } | { "type": "approval.requested", requestId: number, name: string, title: string, input?: Record<string, unknown>, } | { "type": "approval.resolved", requestId: number, decision: ApprovalResolution, } | { "type": "question.requested", requestId: number, questions: Array<Question>, } | { "type": "question.resolved", requestId: number, answers: { [key in string]: string } | null, };

export type Id = { id: string, };

export type IdBlocks = { id: string, blocksJson: string, };

export type IdName = { id: string, name: string, };

export type IdProvider = { id: string, providerSessionId: string, };

export type IdStatus = { id: string, status: string, };

export type Ids = { ids: Array<string>, };

export type Key = { key: string, };

export type KeyValue = { key: string, value: string, };

export type Name = { name: string, };

export type NamePath = { name: string, path: string, };

export type OptionalId = { id: string | null, };

export type PathArg = { path: string, };

export type PathContents = { path: string, contents: string, };

export type ProjectFile = { name: string, path: string, relative: string, };

export type PtyAck = { id: string, processed: number, };

export type PtyAttach = { id: string, from: number, };

export type PtyAttached = { start: number, emitted: number, };

export type PtyError = { id: string, error: string, };

export type PtyExit = { id: string, code: number | null, };

export type PtyKill = { id: string, };

export type PtyResize = { id: string, cols: number, rows: number, };

export type PtySpawn = { id: string, cwd: string, command: Array<string>, cols: number, rows: number, };

export type PtyWrite = { id: string, data: string, };

export type Question = { question: string, header: string, multiSelect: boolean, options: Array<QuestionOption>, };

export type QuestionOption = { label: string, description?: string, };

export type Request = { id: number, method: string, params: unknown, };

export type Response = { id: number, ok: boolean, result?: unknown, error?: string, };

export type Routine = { id: string, sessionId: string, name: string, enabled: boolean, prompt: string, schedule: string, lastRunAt?: number, nextRunAt?: number, runsJson: string, createdBy: string | null, };

export type RoutineMark = { id: string, lastRunAt: number, nextRunAt?: number, runsJson: string, };

export type RoutineUpsert = { id: string | null, sessionId: string, name: string, enabled: boolean, prompt: string, schedule: string, nextRunAt?: number, createdBy: string | null, };

export type ScheduledRoutine = { routine: Routine, session: Session, cwd: string, };

export type Session = { id: string, workspaceId: string, kind: string, name: string, provider: string, model: string, providerSessionId: string | null, description: string, notifications: boolean, autonomy: string, status: string, createdAt: number, updatedAt: number, };

export type SessionCreate = { workspaceId: string, kind: string, name: string, provider: string, model: string, description: string, autonomy: string, };

export type SessionCreated = { session: Session, };

export type SessionId = { sessionId: string, };

export type SessionLine = { sessionId: string, line: string, };

export type SessionStatusEvent = { sessionId: string, status: string, providerSessionId?: string, updatedAt: number, };

export type SessionUpdate = { id: string, name: string, provider: string, model: string, description: string, notifications: boolean, autonomy: string, };

export type TempFile = { extension: string, base64Contents: string, };

export type ToolCall = { id: number, sessionId: string, method: string, params: unknown, };

/**
 * What a tool actually did, normalized across providers. A transcript line
 * reads the same whether it came from Claude's `Bash`, Codex's `exec_command`
 * or opencode's `bash`: the adapters translate into this, and the UI renders
 * one shape instead of four.
 */
export type ToolDetail = { "kind": "command", command: string, exitCode?: number, output?: string, } | { "kind": "file", path: string, lineStart?: number, lineEnd?: number, preview?: string, } | { "kind": "edit", path: string, added: number, removed: number, } | { "kind": "search", query: string, matches?: number, } | { "kind": "fetch", url: string, title?: string, } | { "kind": "message", to: string, text: string, } | { "kind": "output", text: string, };

export type ToolStatus = "pending" | "completed" | "failed" | "interrupted";

export type TranscriptApply = { sessionId: string, seq: number, event: HarnessEvent, };

export type TranscriptSnapshot = { blocks: Array<Block>, working: boolean, status: string, seq: number, };

export type TurnAnswer = { sessionId: string, requestId: number, answers: { [key in string]: string } | null, };

export type TurnRespond = { sessionId: string, requestId: number, decision: ApprovalDecision, };

export type TurnStart = { sessionId: string, cwd: string, text: string, files?: Array<AttachedFile>, mentions?: Array<string>, hidden?: boolean, fresh?: boolean, };

export type TurnStarted = { working: boolean, };

export type TurnUsage = { inputTokens?: number, outputTokens?: number, costUsd?: number, durationMs?: number, };

export type Workspace = { id: string, name: string, path: string, createdAt: number, };

export type WorkspaceId = { workspaceId: string, };
