// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentBinary = { path: string, };

export type AgentExit = { sessionId: string, code: number | null, pid: number, };

export type AgentLines = { sessionId: string, lines: Array<string>, };

export type AgentSpawn = { sessionId: string, command: string, args: Array<string>, cwd: string, env: { [key in string]: string } | null, };

export type Auth = { auth: string, };

export type BridgeInfo = { socketPath: string, token: string, exe: string, };

export type BridgeReply = { id: number, response: unknown, };

export type Cwd = { cwd: string, };

export type DaemonInfo = { url: string, token: string, };

export type Event = { event: string, payload: unknown, };

export type FileBytes = { mime: string, data: string, };

export type Id = { id: string, };

export type IdBlocks = { id: string, blocksJson: string, };

export type IdName = { id: string, name: string, };

export type IdProvider = { id: string, providerSessionId: string, };

export type IdStatus = { id: string, status: string, };

export type Ids = { ids: Array<string>, };

export type Key = { key: string, };

export type KeyValue = { key: string, value: string, };

export type Name = { name: string, };

export type NamePath = { name: string, path: string, };

export type OptionalId = { id: string | null, };

export type PathArg = { path: string, };

export type PathContents = { path: string, contents: string, };

export type ProjectFile = { name: string, path: string, relative: string, };

export type PtyAck = { id: string, processed: number, };

export type PtyAttach = { id: string, from: number, };

export type PtyAttached = { start: number, emitted: number, };

export type PtyError = { id: string, error: string, };

export type PtyExit = { id: string, code: number | null, };

export type PtyKill = { id: string, };

export type PtyResize = { id: string, cols: number, rows: number, };

export type PtySpawn = { id: string, cwd: string, command: Array<string>, cols: number, rows: number, };

export type PtyWrite = { id: string, data: string, };

export type Request = { id: number, method: string, params: unknown, };

export type Response = { id: number, ok: boolean, result?: unknown, error?: string, };

export type Routine = { id: string, sessionId: string, name: string, enabled: boolean, prompt: string, schedule: string, lastRunAt?: number, nextRunAt?: number, runsJson: string, createdBy: string | null, };

export type RoutineMark = { id: string, lastRunAt: number, nextRunAt?: number, runsJson: string, };

export type RoutineUpsert = { id: string | null, sessionId: string, name: string, enabled: boolean, prompt: string, schedule: string, nextRunAt?: number, createdBy: string | null, };

export type ScheduledRoutine = { routine: Routine, session: Session, cwd: string, };

export type Session = { id: string, workspaceId: string, kind: string, name: string, provider: string, model: string, providerSessionId: string | null, description: string, notifications: boolean, autonomy: string, status: string, createdAt: number, updatedAt: number, };

export type SessionCreate = { workspaceId: string, kind: string, name: string, provider: string, model: string, description: string, autonomy: string, };

export type SessionId = { sessionId: string, };

export type SessionLine = { sessionId: string, line: string, };

export type SessionUpdate = { id: string, name: string, provider: string, model: string, description: string, notifications: boolean, autonomy: string, };

export type TempFile = { extension: string, base64Contents: string, };

export type ToolCall = { id: number, sessionId: string, method: string, params: unknown, };

export type Workspace = { id: string, name: string, path: string, createdAt: number, };

export type WorkspaceId = { workspaceId: string, };
