import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowUpRight,
  AtSign,
  Bell,
  Bot,
  Brain,
  Braces,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Calendar,
  CircleAlert,
  CircleCheck,
  CircleMinus,
  CircleX,
  CircleDot,
  CirclePause,
  Clock,
  Code,
  Columns2,
  Copy,
  CornerDownLeft,
  Eye,
  File,
  FileCode,
  FileText,
  Files,
  Filter,
  FolderOpen,
  Globe,
  GripVertical,
  Hash,
  Info,
  Keyboard,
  Layers,
  Link,
  List,
  ListTree,
  Minus,
  MoreHorizontal,
  Network,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Repeat,
  Rows3,
  Search,
  Send,
  Server,
  Settings,
  Sparkles,
  Split,
  Square,
  SquareTerminal,
  Sun,
  Moon,
  Monitor,
  Terminal,
  Trash2,
  Type,
  User,
  Users,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

/**
 * One icon set, one weight. The app had two fighting sets; the rule here is
 * that a glyph that is not in this map does not get drawn.
 */
export const GLYPHS = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  arrowUpRight: ArrowUpRight,
  at: AtSign,
  bell: Bell,
  bot: Bot,
  brain: Brain,
  braces: Braces,
  check: Check,
  checkAll: CheckCheck,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevrons: ChevronsUpDown,
  calendar: Calendar,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  circleMinus: CircleMinus,
  circleX: CircleX,
  circleDot: CircleDot,
  circlePause: CirclePause,
  clock: Clock,
  code: Code,
  columns: Columns2,
  copy: Copy,
  enter: CornerDownLeft,
  eye: Eye,
  file: File,
  fileCode: FileCode,
  fileText: FileText,
  files: Files,
  filter: Filter,
  folder: FolderOpen,
  globe: Globe,
  grip: GripVertical,
  hash: Hash,
  info: Info,
  keyboard: Keyboard,
  layers: Layers,
  link: Link,
  list: List,
  listTree: ListTree,
  minus: Minus,
  more: MoreHorizontal,
  network: Network,
  palette: Palette,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  radio: Radio,
  refresh: RefreshCw,
  repeat: Repeat,
  rows: Rows3,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  sparkles: Sparkles,
  split: Split,
  square: Square,
  squareTerminal: SquareTerminal,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  terminal: Terminal,
  trash: Trash2,
  type: Type,
  user: User,
  users: Users,
  wrench: Wrench,
  x: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} as const;

export type GlyphName = keyof typeof GLYPHS;

export function Icon({
  name,
  size = 16,
  className,
}: {
  name: GlyphName;
  size?: number;
  className?: string;
}) {
  const Glyph = GLYPHS[name];
  return <Glyph size={size} strokeWidth={1.75} className={className} aria-hidden />;
}
